modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "extrartp"
version = "${project_version}"
displayName = "${project_name}"
logoFile = "logo.png"
authors = "Vecoo"
description = "Mod that adds a system of random teleportation across dimensions."

[[dependencies.extrartp]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extrartp]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extrartp]]
modId = "extralib"
mandatory = true
versionRange = "[1.8,)"
ordering = "NONE"
side = "BOTH"