modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="extrartp"
version="1.1.0"
displayName="ExtraRTP"
logoFile ="logo.png"
authors="Vecoo"
description="A mod that adds a system of random teleportation across dimensions."

[[dependencies.extrartp]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.extrartp]]
modId="minecraft"
mandatory=true
versionRange="[1.19,)"
ordering="NONE"
side="BOTH"

[[dependencies.extrartp]]
modId="extralib"
mandatory=true
versionRange="[1.4,)"
ordering="NONE"
side="BOTH"